/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as MRouteImport } from './routes/m'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionSectionIdRouteImport } from './routes/section.$sectionId'
import { Route as MobileMobileRouteImport } from './routes/mobile.mobile'
import { Route as AppSectionIdRoleRouteImport } from './routes/app.$sectionId.$role'
import { Route as ApiPublicPingRouteImport } from './routes/api/public/ping'
import { Route as AppSectionIdRoleTasksRouteImport } from './routes/app.$sectionId.$role.tasks'
import { Route as AppSectionIdRoleSuspendedRouteImport } from './routes/app.$sectionId.$role.suspended'
import { Route as AppSectionIdRoleSuppliersRouteImport } from './routes/app.$sectionId.$role.suppliers'
import { Route as AppSectionIdRoleSettingsRouteImport } from './routes/app.$sectionId.$role.settings'
import { Route as AppSectionIdRoleRepairRouteImport } from './routes/app.$sectionId.$role.repair'
import { Route as AppSectionIdRolePosRouteImport } from './routes/app.$sectionId.$role.pos'
import { Route as AppSectionIdRoleInvoicesRouteImport } from './routes/app.$sectionId.$role.invoices'
import { Route as AppSectionIdRoleInventoryRouteImport } from './routes/app.$sectionId.$role.inventory'
import { Route as AppSectionIdRoleExpensesRouteImport } from './routes/app.$sectionId.$role.expenses'
import { Route as AppSectionIdRoleDebtsRouteImport } from './routes/app.$sectionId.$role.debts'
import { Route as AppSectionIdRoleDashboardRouteImport } from './routes/app.$sectionId.$role.dashboard'
import { Route as AppSectionIdRoleCustomersRouteImport } from './routes/app.$sectionId.$role.customers'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSectionIdRoute = SectionSectionIdRouteImport.update({
  id: '/section/$sectionId',
  path: '/section/$sectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileMobileRoute = MobileMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => MobileRoute,
} as any)
const AppSectionIdRoleRoute = AppSectionIdRoleRouteImport.update({
  id: '/app/$sectionId/$role',
  path: '/app/$sectionId/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPingRoute = ApiPublicPingRouteImport.update({
  id: '/api/public/ping',
  path: '/api/public/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSectionIdRoleTasksRoute = AppSectionIdRoleTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppSectionIdRoleRoute,
} as any)
const AppSectionIdRoleSuspendedRoute =
  AppSectionIdRoleSuspendedRouteImport.update({
    id: '/suspended',
    path: '/suspended',
    getParentRoute: () => AppSectionIdRoleRoute,
  } as any)
const AppSectionIdRoleSuppliersRoute =
  AppSectionIdRoleSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AppSectionIdRoleRoute,
  } as any)
const AppSectionIdRoleSettingsRoute =
  AppSectionIdRoleSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppSectionIdRoleRoute,
  } as any)
const AppSectionIdRoleRepairRoute = AppSectionIdRoleRepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => AppSectionIdRoleRoute,
} as any)
const AppSectionIdRolePosRoute = AppSectionIdRolePosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppSectionIdRoleRoute,
} as any)
const AppSectionIdRoleInvoicesRoute =
  AppSectionIdRoleInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AppSectionIdRoleRoute,
  } as any)
const AppSectionIdRoleInventoryRoute =
  AppSectionIdRoleInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AppSectionIdRoleRoute,
  } as any)
const AppSectionIdRoleExpensesRoute =
  AppSectionIdRoleExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AppSectionIdRoleRoute,
  } as any)
const AppSectionIdRoleDebtsRoute = AppSectionIdRoleDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppSectionIdRoleRoute,
} as any)
const AppSectionIdRoleDashboardRoute =
  AppSectionIdRoleDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppSectionIdRoleRoute,
  } as any)
const AppSectionIdRoleCustomersRoute =
  AppSectionIdRoleCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AppSectionIdRoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/m': typeof MRoute
  '/mobile': typeof MobileRouteWithChildren
  '/owner': typeof OwnerRoute
  '/mobile/mobile': typeof MobileMobileRoute
  '/section/$sectionId': typeof SectionSectionIdRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/app/$sectionId/$role': typeof AppSectionIdRoleRouteWithChildren
  '/app/$sectionId/$role/customers': typeof AppSectionIdRoleCustomersRoute
  '/app/$sectionId/$role/dashboard': typeof AppSectionIdRoleDashboardRoute
  '/app/$sectionId/$role/debts': typeof AppSectionIdRoleDebtsRoute
  '/app/$sectionId/$role/expenses': typeof AppSectionIdRoleExpensesRoute
  '/app/$sectionId/$role/inventory': typeof AppSectionIdRoleInventoryRoute
  '/app/$sectionId/$role/invoices': typeof AppSectionIdRoleInvoicesRoute
  '/app/$sectionId/$role/pos': typeof AppSectionIdRolePosRoute
  '/app/$sectionId/$role/repair': typeof AppSectionIdRoleRepairRoute
  '/app/$sectionId/$role/settings': typeof AppSectionIdRoleSettingsRoute
  '/app/$sectionId/$role/suppliers': typeof AppSectionIdRoleSuppliersRoute
  '/app/$sectionId/$role/suspended': typeof AppSectionIdRoleSuspendedRoute
  '/app/$sectionId/$role/tasks': typeof AppSectionIdRoleTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/m': typeof MRoute
  '/mobile': typeof MobileRouteWithChildren
  '/owner': typeof OwnerRoute
  '/mobile/mobile': typeof MobileMobileRoute
  '/section/$sectionId': typeof SectionSectionIdRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/app/$sectionId/$role': typeof AppSectionIdRoleRouteWithChildren
  '/app/$sectionId/$role/customers': typeof AppSectionIdRoleCustomersRoute
  '/app/$sectionId/$role/dashboard': typeof AppSectionIdRoleDashboardRoute
  '/app/$sectionId/$role/debts': typeof AppSectionIdRoleDebtsRoute
  '/app/$sectionId/$role/expenses': typeof AppSectionIdRoleExpensesRoute
  '/app/$sectionId/$role/inventory': typeof AppSectionIdRoleInventoryRoute
  '/app/$sectionId/$role/invoices': typeof AppSectionIdRoleInvoicesRoute
  '/app/$sectionId/$role/pos': typeof AppSectionIdRolePosRoute
  '/app/$sectionId/$role/repair': typeof AppSectionIdRoleRepairRoute
  '/app/$sectionId/$role/settings': typeof AppSectionIdRoleSettingsRoute
  '/app/$sectionId/$role/suppliers': typeof AppSectionIdRoleSuppliersRoute
  '/app/$sectionId/$role/suspended': typeof AppSectionIdRoleSuspendedRoute
  '/app/$sectionId/$role/tasks': typeof AppSectionIdRoleTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/m': typeof MRoute
  '/mobile': typeof MobileRouteWithChildren
  '/owner': typeof OwnerRoute
  '/mobile/mobile': typeof MobileMobileRoute
  '/section/$sectionId': typeof SectionSectionIdRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/app/$sectionId/$role': typeof AppSectionIdRoleRouteWithChildren
  '/app/$sectionId/$role/customers': typeof AppSectionIdRoleCustomersRoute
  '/app/$sectionId/$role/dashboard': typeof AppSectionIdRoleDashboardRoute
  '/app/$sectionId/$role/debts': typeof AppSectionIdRoleDebtsRoute
  '/app/$sectionId/$role/expenses': typeof AppSectionIdRoleExpensesRoute
  '/app/$sectionId/$role/inventory': typeof AppSectionIdRoleInventoryRoute
  '/app/$sectionId/$role/invoices': typeof AppSectionIdRoleInvoicesRoute
  '/app/$sectionId/$role/pos': typeof AppSectionIdRolePosRoute
  '/app/$sectionId/$role/repair': typeof AppSectionIdRoleRepairRoute
  '/app/$sectionId/$role/settings': typeof AppSectionIdRoleSettingsRoute
  '/app/$sectionId/$role/suppliers': typeof AppSectionIdRoleSuppliersRoute
  '/app/$sectionId/$role/suspended': typeof AppSectionIdRoleSuspendedRoute
  '/app/$sectionId/$role/tasks': typeof AppSectionIdRoleTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/home'
    | '/intro'
    | '/m'
    | '/mobile'
    | '/owner'
    | '/mobile/mobile'
    | '/section/$sectionId'
    | '/api/public/ping'
    | '/app/$sectionId/$role'
    | '/app/$sectionId/$role/customers'
    | '/app/$sectionId/$role/dashboard'
    | '/app/$sectionId/$role/debts'
    | '/app/$sectionId/$role/expenses'
    | '/app/$sectionId/$role/inventory'
    | '/app/$sectionId/$role/invoices'
    | '/app/$sectionId/$role/pos'
    | '/app/$sectionId/$role/repair'
    | '/app/$sectionId/$role/settings'
    | '/app/$sectionId/$role/suppliers'
    | '/app/$sectionId/$role/suspended'
    | '/app/$sectionId/$role/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/home'
    | '/intro'
    | '/m'
    | '/mobile'
    | '/owner'
    | '/mobile/mobile'
    | '/section/$sectionId'
    | '/api/public/ping'
    | '/app/$sectionId/$role'
    | '/app/$sectionId/$role/customers'
    | '/app/$sectionId/$role/dashboard'
    | '/app/$sectionId/$role/debts'
    | '/app/$sectionId/$role/expenses'
    | '/app/$sectionId/$role/inventory'
    | '/app/$sectionId/$role/invoices'
    | '/app/$sectionId/$role/pos'
    | '/app/$sectionId/$role/repair'
    | '/app/$sectionId/$role/settings'
    | '/app/$sectionId/$role/suppliers'
    | '/app/$sectionId/$role/suspended'
    | '/app/$sectionId/$role/tasks'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/home'
    | '/intro'
    | '/m'
    | '/mobile'
    | '/owner'
    | '/mobile/mobile'
    | '/section/$sectionId'
    | '/api/public/ping'
    | '/app/$sectionId/$role'
    | '/app/$sectionId/$role/customers'
    | '/app/$sectionId/$role/dashboard'
    | '/app/$sectionId/$role/debts'
    | '/app/$sectionId/$role/expenses'
    | '/app/$sectionId/$role/inventory'
    | '/app/$sectionId/$role/invoices'
    | '/app/$sectionId/$role/pos'
    | '/app/$sectionId/$role/repair'
    | '/app/$sectionId/$role/settings'
    | '/app/$sectionId/$role/suppliers'
    | '/app/$sectionId/$role/suspended'
    | '/app/$sectionId/$role/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  HomeRoute: typeof HomeRoute
  IntroRoute: typeof IntroRoute
  MRoute: typeof MRoute
  MobileRoute: typeof MobileRouteWithChildren
  OwnerRoute: typeof OwnerRoute
  SectionSectionIdRoute: typeof SectionSectionIdRoute
  ApiPublicPingRoute: typeof ApiPublicPingRoute
  AppSectionIdRoleRoute: typeof AppSectionIdRoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$sectionId': {
      id: '/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/section/$sectionId'
      preLoaderRoute: typeof SectionSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/mobile': {
      id: '/mobile/mobile'
      path: '/mobile'
      fullPath: '/mobile/mobile'
      preLoaderRoute: typeof MobileMobileRouteImport
      parentRoute: typeof MobileRoute
    }
    '/app/$sectionId/$role': {
      id: '/app/$sectionId/$role'
      path: '/app/$sectionId/$role'
      fullPath: '/app/$sectionId/$role'
      preLoaderRoute: typeof AppSectionIdRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ping': {
      id: '/api/public/ping'
      path: '/api/public/ping'
      fullPath: '/api/public/ping'
      preLoaderRoute: typeof ApiPublicPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$sectionId/$role/tasks': {
      id: '/app/$sectionId/$role/tasks'
      path: '/tasks'
      fullPath: '/app/$sectionId/$role/tasks'
      preLoaderRoute: typeof AppSectionIdRoleTasksRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/suspended': {
      id: '/app/$sectionId/$role/suspended'
      path: '/suspended'
      fullPath: '/app/$sectionId/$role/suspended'
      preLoaderRoute: typeof AppSectionIdRoleSuspendedRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/suppliers': {
      id: '/app/$sectionId/$role/suppliers'
      path: '/suppliers'
      fullPath: '/app/$sectionId/$role/suppliers'
      preLoaderRoute: typeof AppSectionIdRoleSuppliersRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/settings': {
      id: '/app/$sectionId/$role/settings'
      path: '/settings'
      fullPath: '/app/$sectionId/$role/settings'
      preLoaderRoute: typeof AppSectionIdRoleSettingsRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/repair': {
      id: '/app/$sectionId/$role/repair'
      path: '/repair'
      fullPath: '/app/$sectionId/$role/repair'
      preLoaderRoute: typeof AppSectionIdRoleRepairRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/pos': {
      id: '/app/$sectionId/$role/pos'
      path: '/pos'
      fullPath: '/app/$sectionId/$role/pos'
      preLoaderRoute: typeof AppSectionIdRolePosRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/invoices': {
      id: '/app/$sectionId/$role/invoices'
      path: '/invoices'
      fullPath: '/app/$sectionId/$role/invoices'
      preLoaderRoute: typeof AppSectionIdRoleInvoicesRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/inventory': {
      id: '/app/$sectionId/$role/inventory'
      path: '/inventory'
      fullPath: '/app/$sectionId/$role/inventory'
      preLoaderRoute: typeof AppSectionIdRoleInventoryRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/expenses': {
      id: '/app/$sectionId/$role/expenses'
      path: '/expenses'
      fullPath: '/app/$sectionId/$role/expenses'
      preLoaderRoute: typeof AppSectionIdRoleExpensesRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/debts': {
      id: '/app/$sectionId/$role/debts'
      path: '/debts'
      fullPath: '/app/$sectionId/$role/debts'
      preLoaderRoute: typeof AppSectionIdRoleDebtsRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/dashboard': {
      id: '/app/$sectionId/$role/dashboard'
      path: '/dashboard'
      fullPath: '/app/$sectionId/$role/dashboard'
      preLoaderRoute: typeof AppSectionIdRoleDashboardRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
    '/app/$sectionId/$role/customers': {
      id: '/app/$sectionId/$role/customers'
      path: '/customers'
      fullPath: '/app/$sectionId/$role/customers'
      preLoaderRoute: typeof AppSectionIdRoleCustomersRouteImport
      parentRoute: typeof AppSectionIdRoleRoute
    }
  }
}

interface MobileRouteChildren {
  MobileMobileRoute: typeof MobileMobileRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileMobileRoute: MobileMobileRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

interface AppSectionIdRoleRouteChildren {
  AppSectionIdRoleCustomersRoute: typeof AppSectionIdRoleCustomersRoute
  AppSectionIdRoleDashboardRoute: typeof AppSectionIdRoleDashboardRoute
  AppSectionIdRoleDebtsRoute: typeof AppSectionIdRoleDebtsRoute
  AppSectionIdRoleExpensesRoute: typeof AppSectionIdRoleExpensesRoute
  AppSectionIdRoleInventoryRoute: typeof AppSectionIdRoleInventoryRoute
  AppSectionIdRoleInvoicesRoute: typeof AppSectionIdRoleInvoicesRoute
  AppSectionIdRolePosRoute: typeof AppSectionIdRolePosRoute
  AppSectionIdRoleRepairRoute: typeof AppSectionIdRoleRepairRoute
  AppSectionIdRoleSettingsRoute: typeof AppSectionIdRoleSettingsRoute
  AppSectionIdRoleSuppliersRoute: typeof AppSectionIdRoleSuppliersRoute
  AppSectionIdRoleSuspendedRoute: typeof AppSectionIdRoleSuspendedRoute
  AppSectionIdRoleTasksRoute: typeof AppSectionIdRoleTasksRoute
}

const AppSectionIdRoleRouteChildren: AppSectionIdRoleRouteChildren = {
  AppSectionIdRoleCustomersRoute: AppSectionIdRoleCustomersRoute,
  AppSectionIdRoleDashboardRoute: AppSectionIdRoleDashboardRoute,
  AppSectionIdRoleDebtsRoute: AppSectionIdRoleDebtsRoute,
  AppSectionIdRoleExpensesRoute: AppSectionIdRoleExpensesRoute,
  AppSectionIdRoleInventoryRoute: AppSectionIdRoleInventoryRoute,
  AppSectionIdRoleInvoicesRoute: AppSectionIdRoleInvoicesRoute,
  AppSectionIdRolePosRoute: AppSectionIdRolePosRoute,
  AppSectionIdRoleRepairRoute: AppSectionIdRoleRepairRoute,
  AppSectionIdRoleSettingsRoute: AppSectionIdRoleSettingsRoute,
  AppSectionIdRoleSuppliersRoute: AppSectionIdRoleSuppliersRoute,
  AppSectionIdRoleSuspendedRoute: AppSectionIdRoleSuspendedRoute,
  AppSectionIdRoleTasksRoute: AppSectionIdRoleTasksRoute,
}

const AppSectionIdRoleRouteWithChildren =
  AppSectionIdRoleRoute._addFileChildren(AppSectionIdRoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  HomeRoute: HomeRoute,
  IntroRoute: IntroRoute,
  MRoute: MRoute,
  MobileRoute: MobileRouteWithChildren,
  OwnerRoute: OwnerRoute,
  SectionSectionIdRoute: SectionSectionIdRoute,
  ApiPublicPingRoute: ApiPublicPingRoute,
  AppSectionIdRoleRoute: AppSectionIdRoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
